In [2]:
import numpy as np

# 1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin


In [5]:


arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [7]:
arr3d.ndim

3

# 2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.


In [8]:
soru2=np.arange(34,113,6)
soru2

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

# 3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)


In [9]:
np.linspace(50,500,91)

array([ 50.,  55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.,
       105., 110., 115., 120., 125., 130., 135., 140., 145., 150., 155.,
       160., 165., 170., 175., 180., 185., 190., 195., 200., 205., 210.,
       215., 220., 225., 230., 235., 240., 245., 250., 255., 260., 265.,
       270., 275., 280., 285., 290., 295., 300., 305., 310., 315., 320.,
       325., 330., 335., 340., 345., 350., 355., 360., 365., 370., 375.,
       380., 385., 390., 395., 400., 405., 410., 415., 420., 425., 430.,
       435., 440., 445., 450., 455., 460., 465., 470., 475., 480., 485.,
       490., 495., 500.])

# 4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.


In [10]:
np.logspace(2,5,8)


array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

#5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.


In [13]:
np.array([[0,1,2],[3,4,5],[6,7,8]])



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)


In [15]:
np.zeros((6,6),dtype='int')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# 7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)


In [16]:

np.ones((4,4),dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# 8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)


In [17]:
np.eye(8,dtype='int')

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

# 9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)


In [22]:
birim=np.eye(5,dtype='int')
birim[birim==1]=3
birim

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

# 10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

In [23]:

np.random.rand(6)

array([0.35621389, 0.0311361 , 0.88375841, 0.75340267, 0.38971878,
       0.55140951])

# 11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) 
# tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

In [30]:

a=np.random.randint(low=50, high=101, size=(5,2))
a


array([[75, 75],
       [95, 51],
       [66, 63],
       [62, 57],
       [52, 56]])

In [27]:
a.shape

(5, 2)

# 12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan
#     (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

In [6]:


np.linspace(50,1000,50)

array([  50.        ,   69.3877551 ,   88.7755102 ,  108.16326531,
        127.55102041,  146.93877551,  166.32653061,  185.71428571,
        205.10204082,  224.48979592,  243.87755102,  263.26530612,
        282.65306122,  302.04081633,  321.42857143,  340.81632653,
        360.20408163,  379.59183673,  398.97959184,  418.36734694,
        437.75510204,  457.14285714,  476.53061224,  495.91836735,
        515.30612245,  534.69387755,  554.08163265,  573.46938776,
        592.85714286,  612.24489796,  631.63265306,  651.02040816,
        670.40816327,  689.79591837,  709.18367347,  728.57142857,
        747.95918367,  767.34693878,  786.73469388,  806.12244898,
        825.51020408,  844.89795918,  864.28571429,  883.67346939,
        903.06122449,  922.44897959,  941.83673469,  961.2244898 ,
        980.6122449 , 1000.        ])

# 13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun.
# Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

In [11]:


a=np.random.randint(0,101,10)
a

array([78,  8,  9, 91, 73, 52, 56, 66, 38, 13])

In [12]:
a.max()

91

In [13]:
a.min()

8

# 14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5)
# shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 
# 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

In [ ]:
# 15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35.
# indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.
