# NumPy Exercises

Bu zamana kadar gördüğümüz konularla alakalı bilgilerimizi test edelim

<div class="alert alert-danger" style="margin: 10px"><strong>Uyarı!</strong> Output'un üstündeki kod hücrelerini çalıştırmayın !, <br>Aksi takdirde notebooktaki cevap outputlarını kaybedebilirsiniz!</div>

#### 1. NumPy kütüphanesi np kısaltması ile import edin

In [5]:
import numpy as np

#### 2. Let's create an array 10 pcs values 0 .

In [6]:
# Write your codes here
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
# dont't Write your codes here !

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Let's create an array 10 pcs values 1 .

In [76]:
np.array([1]*10)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [3]:
# dont't Write your codes here !

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Let's create an array 10 pcs values 5.

In [11]:
np.array([5]*10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [4]:
# dont't Write your codes here !

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. let's Create adn array of consecutive integer from 10 to 50. (including 10 and 50) 

In [13]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
# dont't Write your codes here !

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Lets's Create an array of even integers between 10 nd 50. (including 10 and 50).

In [14]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
# dont't Write your codes here !

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. let's create an array of 9 integers 0 to 8 in a 3x3 Shapee.

In [15]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# dont't Write your codes here !

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Create a 3x3 unit matrix

In [17]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# dont't Write your codes here !

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Generate a random number from 0-1 using NumPy. <br><br>&emsp;NOTE: Your answer will be different from the output below

In [18]:
np.random.rand(1)

array([0.00710326])

In [9]:
# dont't Write your codes here !

array([0.65248055])

#### 10. Let's create an array of 25 random numbers with standard distribution using NumPy. <br><br>&emsp;&ensp;NOTE: Your answer will be different from the output below

In [20]:
np.random.normal(loc=0, scale=1, size=(5,5))

array([[-0.05210811,  1.24010496,  1.21044679,  0.13580103,  1.99369316],
       [ 1.88546154, -0.19195322,  2.69696407,  1.54350408,  1.2000348 ],
       [-0.30143108,  0.5874788 ,  0.2222123 , -0.07926607, -2.04888286],
       [-1.60070011,  1.16142334,  0.18936534, -0.1948577 , -0.67652577],
       [ 2.35680863, -0.94093236, -1.59720593,  0.1996782 , -0.4973893 ]])

In [10]:
# dont't Write your codes here !

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Try to create array like below output

In [22]:
arr=np.arange(0.01 , 1.01 , 0.01)
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
# dont't Write your codes here !

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Create an array of 20 numbers in linear increments from 0-1:

In [23]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
# dont't Write your codes here !

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## NumPy Indexing and Selection

The matrix below is our starting matrix for the next questions. (Continue by running the code cell below.), try to answer the questions we asked below:


In [24]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Try to create the matrices given below.<br><br>&emsp;&ensp;Do not run the code cell above the outputs otherwise you will not be able to see the outputs

In [54]:
#  Write your codes here 

alt_mat = mat[2:5, 1:5]
alt_mat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# dont't Write your codes here !

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Write code that reproduces the output shown below.

In [57]:
arr1=mat[3][4]
arr1

20

In [15]:
# dont't Write your codes here !

20

#### 15. Using the mat array, create the codes that will output the following matrix

In [66]:
arr=mat[0:3, 1].reshape(3,1)
arr


array([[ 2],
       [ 7],
       [12]])

In [16]:
# dont't Write your codes here !

array([[ 2],
       [ 7],
       [12]])

#### 16. Using the mat array, create the codes that will output the following matrix

In [68]:
arr2=mat[4]
arr2

array([21, 22, 23, 24, 25])

In [17]:
# dont't Write your codes here !

array([21, 22, 23, 24, 25])

#### 17. Using the mat array, create the codes that will output the following matrix

In [71]:
arr=mat[3:]
arr

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
# dont't Write your codes here !

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy Operations

#### 18. Mat arrayindeki bütün değerlerin toplamını bulun

In [73]:
arr3=np.sum(mat)
arr3

325

In [19]:
# dont't Write your codes here !

325

#### 19. Find the standard deviation of the values ​​in the mat array

In [74]:
arr4=np.std(mat)
arr4

7.211102550927978

In [20]:
# dont't Write your codes here !

7.211102550927978

#### 20. Create a new array by finding the sum of each column in the mat array

In [75]:
arr5=np.sum(mat,axis=0)
arr5

array([55, 60, 65, 70, 75])

In [21]:
# dont't Write your codes here !

array([55, 60, 65, 70, 75])

# Congratulations, NumPy basics learned!